version: "3"
services:
  hapi-fhir-jpaserver-start:
    build: .
    container_name: hapi-fhir-jpaserver-start
    restart: on-failure
    ports:
      - "8080:8080"
    network_mode: "host"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://127.0.0.1:5432/hapi_r4"
      SPRING_DATASOURCE_USERNAME: "postgres"
      SPRING_DATASOURCE_PASSWORD: "postgres"  # Replace with the actual password
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: "org.postgresql.Driver"
      SPRING_JPA_DATABASE_PLATFORM: "org.hibernate.dialect.PostgreSQLDialect"
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: "org.hibernate.dialect.PostgreSQLDialect"
      SPRING_JPA_HIBERNATE_DDL_AUTO: "update"  # Adjust according to your needs
      SPRING_JPA_SHOW_SQL: "true"

